main: net.minez2.CraftZChests.Main
name: CraftZChests
version: 1.1
author: kwilk
api-version: 1.13
description: Custom chest regeneration with loottables

commands:
  chestregen:
    aliases: cr